"""Planning-to-evaluation deep research engine."""

from .adversarial import BlueTeamRepairer, RedTeamReviewer, ReviewConvergence
from .agents import (
    CallableSearchBackend,
    LocalHybridSearchBackend,
    ResearchWorker,
    SearchBackend,
    Synthesizer,
)
from .config import ResearchConfig
from .claims import ClaimEvidenceVerifier, extract_claims
from .env import load_env_files
from .harness import (
    AgentExecutionResult,
    AgentRuntime,
    AgentSpec,
    LegacyAgentAdapter,
    LocalAgentRuntime,
    RetrievalTool,
    RetrievalToolAdapter,
    RoleAwareAgentAdapter,
    RunContext,
    ToolRegistry,
)
from .memory import HashingEmbedder, SharedMemory, textrank_compress
from .llm_backends import (
    LLMBackendConfig,
    LLMProvider,
    OpenAICompatibleLLM,
    auto_provider,
    backend_config,
    build_llm,
)
from .orchestrator import DeepResearchAgent
from .planner import HeuristicPlanner, LLMPlanner, Planner
from .schemas import (
    ClaimEvidenceLink,
    ClaimLedger,
    ClaimRecord,
    CompletionStatus,
    Evidence,
    PatchApplicationResult,
    PatchPosition,
    PatchRejection,
    RepairAction,
    ReportPatch,
    ResearchPlan,
    ResearchResult,
    ResearchSubtask,
    ReviewIssue,
    ReviewResult,
    SupportVerdict,
    TaskStatus,
)
from .security import SecurityScanResult, sanitize_untrusted_content
from .swarm import (
    BudgetController,
    BudgetResource,
    ComplexityLevel,
    HeuristicSwarmPolicy,
    SwarmPlan,
    SwarmPolicy,
)
from .web_backends import CompositeSearchBackend, TavilySearchBackend

__all__ = [
    "BlueTeamRepairer",
    "BudgetController",
    "BudgetResource",
    "AgentExecutionResult",
    "AgentRuntime",
    "AgentSpec",
    "ClaimEvidenceLink",
    "ClaimEvidenceVerifier",
    "ClaimLedger",
    "ClaimRecord",
    "CompletionStatus",
    "CallableSearchBackend",
    "CompositeSearchBackend",
    "ComplexityLevel",
    "DeepResearchAgent",
    "Evidence",
    "PatchApplicationResult",
    "PatchPosition",
    "PatchRejection",
    "HashingEmbedder",
    "HeuristicPlanner",
    "HeuristicSwarmPolicy",
    "LLMPlanner",
    "LocalHybridSearchBackend",
    "LegacyAgentAdapter",
    "LocalAgentRuntime",
    "load_env_files",
    "LLMBackendConfig",
    "LLMProvider",
    "OpenAICompatibleLLM",
    "Planner",
    "RedTeamReviewer",
    "RepairAction",
    "ReportPatch",
    "ResearchConfig",
    "ResearchPlan",
    "ResearchResult",
    "ResearchSubtask",
    "ResearchWorker",
    "RetrievalTool",
    "RetrievalToolAdapter",
    "RoleAwareAgentAdapter",
    "ReviewConvergence",
    "ReviewIssue",
    "ReviewResult",
    "SearchBackend",
    "SecurityScanResult",
    "SharedMemory",
    "RunContext",
    "SupportVerdict",
    "SwarmPlan",
    "SwarmPolicy",
    "Synthesizer",
    "TaskStatus",
    "TavilySearchBackend",
    "ToolRegistry",
    "textrank_compress",
    "auto_provider",
    "backend_config",
    "build_llm",
    "extract_claims",
    "sanitize_untrusted_content",
]
